services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\: # là on lui dit tu vas me charger tout ce qui commence par App
    resource: "../src" # et tu vas trouver cela dans le dossier src

  App\Controller\OrderController:
    public: true

  Symfony\Component\EventDispatcher\EventDispatcher:
    calls:
      - method: 'addListener'
        arguments:
          - 'order.after_insert'
          - ['@App\Listener\OrderSmsListener', 'sendSmsToBuyer']
          - 10
      - method: 'addSubscriber'
        arguments: ['@App\Listener\OrderEmailsSubscriber']
